apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: kosmo-public-alerts-slack
  labels:
    helm.sh/chart: '{{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}'
    app.kubernetes.io/name: kosmo-monitoring
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
spec:
  route:
    receiver: slack-kosmo-public
    groupBy:
      - cluster
      - namespace
      - alertname
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 4h
    matchers:
      - name: alertname
        value: KosmoPublicEndpointDown|KosmoPublicEndpointHighLatency
        matchType: =~
  receivers:
    - name: slack-kosmo-public
      slackConfigs:
        - apiURL:
            name: alertmanager-slack-webhook
            key: SLACK_WEBHOOK_URL
          channel: '#monitoring'
          sendResolved: true
