apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: alertmanager-slack-webhook
  labels:
    helm.sh/chart: '{{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}'
    app.kubernetes.io/name: kosmo-monitoring
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
spec:
  vaultAuthRef: vso-kubernetes-sync
  mount: secret
  type: kv-v2
  path: kubernetes/alertmanager/slack
  refreshAfter: 5m
  destination:
    name: alertmanager-slack-webhook
    create: true
    overwrite: true
    type: Opaque
    transformation:
      includes:
        - ^SLACK_WEBHOOK_URL$
