env:
image: ghcr.io/byulmaru/kosmo
imageDigest: ''
version: main
admin:
  enabled: false
  replicas:
    dev: 1
    prod: 2
  health:
    port: 8080
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi
  tailscale:
    hostname: ''
    fqdn: ''
    namespace: tailscale
    proxyPodLabels: {}
worker:
  replicas:
    dev: 1
    prod: 2
  health:
    port: 8080
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
autoscaling:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
migration:
  enabled: false
fedify:
  consumer:
    replicas:
      dev: 1
      prod: 2
    health:
      port: 8080
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
temporal:
  frontendAddress: temporal-frontend.temporal.svc.cluster.local:7233
  adminTools:
    image: temporalio/admin-tools
    digest: sha256:dbc5fcd6ee8f0f4d808bf765af9a87dea9d8a283abfdcfbd2fc148496ba66107
  namespace:
    ownerEmail: dev@byulmaru.co
    names:
      dev: kosmo-dev
      prod: kosmo-prod
    retentions:
      dev: 3d
      prod: 30d
postgres:
  resources:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      cpu: 250m
      memory: 1Gi
  pooler:
    replicas:
      dev: 1
      prod: 3
    maxClientConnections: 1000
    defaultPoolSize: 10
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 250m
        memory: 128Mi
