env:
image: ghcr.io/byulmaru/kosmo
imageDigest: ''
version: main
workloads:
  enabled: true
autoscaling:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
migration:
  enabled: false
postgres:
  resources:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      cpu: 250m
      memory: 1Gi
