apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kosmo
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
            namespace: kosmo-dev
            webDomain: dev.kos.moe
            apiDomain: dev-api.kos.moe
            image: ghcr.io/byulmaru/kosmo
            version: main
  template:
    metadata:
      name: 'kosmo-{{env}}'
    spec:
      project: kosmo
      source:
        repoURL: https://github.com/byulmaru/kosmo.git
        targetRevision: main
        path: apps/helm
        helm:
          releaseName: kosmo
          values: |
            env: '{{env}}'
            webDomain: '{{webDomain}}'
            apiDomain: '{{apiDomain}}'
            image: '{{image}}'
            version: '{{version}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
