apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kosmo-expo
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: expo=ghcr.io/byulmaru/kosmo-web:latest
    argocd-image-updater.argoproj.io/expo.update-strategy: digest
    argocd-image-updater.argoproj.io/expo.helm.image-name: expo.image.repository
    argocd-image-updater.argoproj.io/expo.helm.image-tag: expo.image.tag
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: byulmaru
  source:
    repoURL: https://github.com/byulmaru/kosmo.git
    targetRevision: main
    path: apps/helm
    helm:
      releaseName: kosmo
      parameters:
        - name: expo.image.repository
          value: ghcr.io/byulmaru/kosmo-web
        - name: expo.image.tag
          value: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: kosmo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
