packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@mongodb-js/zstd'
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - msw
  - sharp
  - unrs-resolver

overrides:
  '@eslint/plugin-kit@<0.3.4': '>=0.3.4'
  '@fedify/fedify@>=1.8.0 <1.8.15': '>=1.8.15'
  '@smithy/config-resolver@<4.4.0': '>=4.4.0'
  cookie@<0.7.0: '>=0.7.0'
  esbuild@<=0.24.2: '>=0.25.0'
  hono@<4.10.3: '>=4.10.3'
  hono@<4.11.4: '>=4.11.4'
  hono@<4.9.7: '>=4.9.7'
  hono@>=1.1.0 <4.10.2: '>=4.10.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  undici@<6.23.0: '>=6.23.0'
