packages:
  - apps/*
  - packages/*

enableGlobalVirtualStore: true
pmOnFail: ignore
minimumReleaseAge: 4320
allowBuilds:
  '@fission-ai/openspec': true
  '@tailwindcss/oxide': true
  core-js: true
  esbuild: true
  unrs-resolver: true
