/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainAtChar123handleChar125RouteImport } from './routes/_main/@{$handle}'
import { Route as MainAtChar123handleChar125FollowingRouteImport } from './routes/_main/@{$handle}/following'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainAtChar123handleChar125Route =
  MainAtChar123handleChar125RouteImport.update({
    id: '/@{$handle}',
    path: '/@{$handle}',
    getParentRoute: () => MainRoute,
  } as any)
const MainAtChar123handleChar125FollowingRoute =
  MainAtChar123handleChar125FollowingRouteImport.update({
    id: '/following',
    path: '/following',
    getParentRoute: () => MainAtChar123handleChar125Route,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/@{$handle}': typeof MainAtChar123handleChar125RouteWithChildren
  '/@{$handle}/following': typeof MainAtChar123handleChar125FollowingRoute
}
export interface FileRoutesByTo {
  '/@{$handle}': typeof MainAtChar123handleChar125RouteWithChildren
  '/': typeof MainIndexRoute
  '/@{$handle}/following': typeof MainAtChar123handleChar125FollowingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/_main/@{$handle}': typeof MainAtChar123handleChar125RouteWithChildren
  '/_main/': typeof MainIndexRoute
  '/_main/@{$handle}/following': typeof MainAtChar123handleChar125FollowingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/@{$handle}' | '/@{$handle}/following'
  fileRoutesByTo: FileRoutesByTo
  to: '/@{$handle}' | '/' | '/@{$handle}/following'
  id:
    | '__root__'
    | '/_main'
    | '/_main/@{$handle}'
    | '/_main/'
    | '/_main/@{$handle}/following'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/@{$handle}': {
      id: '/_main/@{$handle}'
      path: '/@{$handle}'
      fullPath: '/@{$handle}'
      preLoaderRoute: typeof MainAtChar123handleChar125RouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/@{$handle}/following': {
      id: '/_main/@{$handle}/following'
      path: '/following'
      fullPath: '/@{$handle}/following'
      preLoaderRoute: typeof MainAtChar123handleChar125FollowingRouteImport
      parentRoute: typeof MainAtChar123handleChar125Route
    }
  }
}

interface MainAtChar123handleChar125RouteChildren {
  MainAtChar123handleChar125FollowingRoute: typeof MainAtChar123handleChar125FollowingRoute
}

const MainAtChar123handleChar125RouteChildren: MainAtChar123handleChar125RouteChildren =
  {
    MainAtChar123handleChar125FollowingRoute:
      MainAtChar123handleChar125FollowingRoute,
  }

const MainAtChar123handleChar125RouteWithChildren =
  MainAtChar123handleChar125Route._addFileChildren(
    MainAtChar123handleChar125RouteChildren,
  )

interface MainRouteChildren {
  MainAtChar123handleChar125Route: typeof MainAtChar123handleChar125RouteWithChildren
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainAtChar123handleChar125Route: MainAtChar123handleChar125RouteWithChildren,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
