{{- $certificate := .Values.certificate -}}
{{- if $certificate.enabled }}
{{- $defaultSecretName := printf "%s-expo-tls" .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- $secretName := default $defaultSecretName $certificate.secretName -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $secretName }}
spec:
  secretName: {{ $secretName }}
  issuerRef:
    name: {{ $certificate.issuerRef.name }}
    kind: {{ $certificate.issuerRef.kind }}
  dnsNames:
    {{- toYaml $certificate.dnsNames | nindent 4 }}
{{- end }}
