{{- $infisical := .Values.infisical -}}
{{- if $infisical.enabled }}
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: {{ printf "%s-env" .Release.Name | trunc 63 | trimSuffix "-" }}
  labels:
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/name: env
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  authentication:
    kubernetesAuth:
      identityId: {{ $infisical.identityId }}
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: secret
        namespace: infisical
      secretsScope:
        projectId: {{ $infisical.projectId }}
        envSlug: {{ $infisical.envSlug }}
        secretsPath: /
  managedKubeSecretReferences:
    - secretName: {{ $infisical.secretName }}
      secretNamespace: {{ .Release.Namespace }}
      creationPolicy: Owner
{{- end }}
