apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "kosmo.postgresName" . }}
{{- if eq .Values.env "prod" }}
  annotations:
    argocd.argoproj.io/sync-options: Prune=confirm
{{- end }}
  labels:
    helm.sh/chart: {{ include "kosmo.chart" . }}
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  instances: {{ ternary 3 1 (eq .Values.env "prod") }}
{{- if eq .Values.env "dev" }}
  enablePDB: false
{{- end }}
  resources:
{{ toYaml .Values.postgres.resources | indent 4 }}
{{- $apiCertificateEnabled := eq (include "kosmo.postgresCredentialClientCertificateIsConfigured" (list . "api") | trim) "true" -}}
{{- $workerCertificateEnabled := eq (include "kosmo.postgresCredentialClientCertificateIsConfigured" (list . "worker") | trim) "true" -}}
{{- if eq .Values.env "prod" }}
  serviceAccountName: kosmo-postgres-backup
{{- end }}
{{- if or $apiCertificateEnabled $workerCertificateEnabled (eq .Values.env "prod") }}
  postgresql:
{{- if $apiCertificateEnabled }}
    pg_hba:
      - "hostssl kosmo kosmo_api all cert"
      - "hostnossl kosmo kosmo_api all reject"
{{- if $workerCertificateEnabled }}
      - "hostssl kosmo kosmo_worker all cert"
      - "hostnossl kosmo kosmo_worker all reject"
{{- end }}
{{- else if $workerCertificateEnabled }}
    pg_hba:
      - "hostssl kosmo kosmo_worker all cert"
      - "hostnossl kosmo kosmo_worker all reject"
{{- end }}
{{- if eq .Values.env "prod" }}
    parameters:
      archive_timeout: 4min
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: kosmo-postgres-backup
{{- end }}
{{- end }}
  bootstrap:
    initdb:
      database: kosmo
      owner: kosmo
  storage:
    size: 10Gi
