{{- if eq .Values.env "prod" }}
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: {{ printf "%s-postgres-migration" .Release.Name | trunc 63 | trimSuffix "-" }}
  annotations:
    argocd.argoproj.io/sync-options: Prune=confirm
  labels:
    helm.sh/chart: {{ include "kosmo.chart" . }}
    app.kubernetes.io/name: postgres-migration
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  cluster:
    name: {{ include "kosmo.postgresName" . }}
  name: kosmo_migration
  login: true
  superuser: false
  inRoles:
    - kosmo
  passwordSecret:
    name: {{ printf "%s-postgres-migration" .Release.Name | trunc 63 | trimSuffix "-" }}
  databaseRoleReclaimPolicy: retain
{{- end }}
