{{- $releaseName := .Release.Name | trunc 47 | trimSuffix "-" }}
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: {{ printf "%s-postgres-api" $releaseName }}
  annotations:
    argocd.argoproj.io/sync-options: Prune=confirm
  labels:
    helm.sh/chart: {{ include "kosmo.chart" . }}
    app.kubernetes.io/name: postgres-api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  cluster:
    name: {{ include "kosmo.postgresName" . }}
  name: kosmo_api
  login: true
  inherit: true
  superuser: false
  createdb: false
  createrole: false
  replication: false
  bypassrls: false
  inRoles: []
  passwordSecret:
    name: {{ printf "%s-postgres-api" $releaseName }}
  databaseRoleReclaimPolicy: retain
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: {{ include "kosmo.fedifyQueueResourceName" . }}
  annotations:
    argocd.argoproj.io/sync-options: Prune=confirm
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    helm.sh/chart: {{ include "kosmo.chart" . }}
    app.kubernetes.io/name: postgres-fedify-queue
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  cluster:
    name: {{ include "kosmo.postgresName" . }}
  name: kosmo_fedify_queue
  login: true
  inherit: true
  superuser: false
  createdb: false
  createrole: false
  replication: false
  bypassrls: false
  inRoles: []
  passwordSecret:
    name: {{ include "kosmo.fedifyQueueResourceName" . | quote }}
  databaseRoleReclaimPolicy: retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: {{ printf "%s-postgres-fedify-queue-database" (.Release.Name | trunc 32 | trimSuffix "-") }}
  annotations:
    argocd.argoproj.io/sync-options: Prune=confirm
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    helm.sh/chart: {{ include "kosmo.chart" . }}
    app.kubernetes.io/name: postgres-fedify-queue-database
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  cluster:
    name: {{ include "kosmo.postgresName" . }}
  name: kosmo_fedify_queue
  owner: kosmo_fedify_queue
  databaseReclaimPolicy: retain
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: {{ printf "%s-postgres-worker" $releaseName }}
  annotations:
    argocd.argoproj.io/sync-options: Prune=confirm
  labels:
    helm.sh/chart: {{ include "kosmo.chart" . }}
    app.kubernetes.io/name: postgres-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  cluster:
    name: {{ include "kosmo.postgresName" . }}
  name: kosmo_worker
  login: true
  inherit: true
  superuser: false
  createdb: false
  createrole: false
  replication: false
  bypassrls: true
  inRoles: []
  passwordSecret:
    name: {{ printf "%s-postgres-worker" $releaseName }}
  databaseRoleReclaimPolicy: retain
