{{- if eq .Values.env "prod" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kosmo-postgres-backup
  labels:
    helm.sh/chart: {{ include "kosmo.chart" . }}
    app.kubernetes.io/name: postgres-backup
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: kosmo-postgres-backup
  annotations:
    argocd.argoproj.io/sync-options: Prune=confirm
  labels:
    helm.sh/chart: {{ include "kosmo.chart" . }}
    app.kubernetes.io/name: postgres-backup
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  configuration:
    destinationPath: s3://byulmaru-kosmo-prod-postgresql-backups-822638974464/kosmo-prod/
    s3Credentials:
      inheritFromIAMRole: true
  retentionPolicy: 7d
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: kosmo-postgres-daily
  labels:
    helm.sh/chart: {{ include "kosmo.chart" . }}
    app.kubernetes.io/name: postgres-backup
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  schedule: "0 0 18 * * *"
  backupOwnerReference: self
  cluster:
    name: {{ include "kosmo.postgresName" . }}
  immediate: true
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
{{- end }}
