apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "kosmo.postgresName" . }}
{{- if eq .Values.env "prod" }}
  annotations:
    argocd.argoproj.io/sync-options: Prune=confirm
{{- end }}
  labels:
    helm.sh/chart: {{ include "kosmo.chart" . }}
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  instances: {{ ternary 3 1 (eq .Values.env "prod") }}
{{- if eq .Values.env "dev" }}
  enablePDB: false
  resources:
{{ toYaml .Values.postgres.devResources | indent 4 }}
{{- end }}
{{- if eq .Values.env "prod" }}
  serviceAccountName: kosmo-postgres-backup
  postgresql:
    parameters:
      archive_timeout: 4min
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: kosmo-postgres-backup
{{- end }}
  bootstrap:
    initdb:
      database: kosmo
      owner: kosmo
  storage:
    size: 10Gi
