{{- $env := .Values.env -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "vault-secrets-sync"
  labels:
    helm.sh/chart: {{ include "kosmo.chart" . }}
    app.kubernetes.io/name: env
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: "vso-kubernetes-sync"
  labels:
    helm.sh/chart: {{ include "kosmo.chart" . }}
    app.kubernetes.io/name: env
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  method: "kubernetes"
  mount: "kubernetes"
  kubernetes:
    role: "vso-kubernetes-sync"
    serviceAccount: "vault-secrets-sync"
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: "env"
  labels:
    helm.sh/chart: {{ include "kosmo.chart" . }}
    app.kubernetes.io/name: env
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  vaultAuthRef: "vso-kubernetes-sync"
  mount: "secret"
  type: "kv-v2"
  path: {{ printf "kubernetes/kosmo/%s" $env | quote }}
  refreshAfter: "5m"
  destination:
    name: "env"
    create: true
    overwrite: true
    type: "Opaque"
  rolloutRestartTargets:
    - kind: "Rollout"
      name: {{ printf "%s-web" .Release.Name | trunc 63 | trimSuffix "-" | quote }}
    - kind: "Rollout"
      name: {{ printf "%s-api" .Release.Name | trunc 63 | trimSuffix "-" | quote }}
