{{- $env := .Values.env -}}
{{- $releaseName := .Release.Name | trunc 47 | trimSuffix "-" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "vault-secrets-sync"
  labels:
    helm.sh/chart: {{ include "kosmo.chart" . }}
    app.kubernetes.io/name: env
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: "vso-kubernetes-sync"
  labels:
    helm.sh/chart: {{ include "kosmo.chart" . }}
    app.kubernetes.io/name: env
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  method: "kubernetes"
  mount: "kubernetes"
  kubernetes:
    role: "vso-kubernetes-sync"
    serviceAccount: "vault-secrets-sync"
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: "env"
  labels:
    helm.sh/chart: {{ include "kosmo.chart" . }}
    app.kubernetes.io/name: env
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  vaultAuthRef: "vso-kubernetes-sync"
  mount: "secret"
  type: "kv-v2"
  path: {{ printf "kubernetes/kosmo/%s" $env | quote }}
  refreshAfter: "5m"
  destination:
    name: "env"
    create: true
    overwrite: true
    type: "Opaque"
  {{- if .Values.workloads.enabled }}
  rolloutRestartTargets:
    - kind: "argo.Rollout"
      name: {{ printf "%s-web" .Release.Name | trunc 63 | trimSuffix "-" | quote }}
    - kind: "argo.Rollout"
      name: {{ printf "%s-api" .Release.Name | trunc 63 | trimSuffix "-" | quote }}
  {{- end }}
{{- if eq .Values.env "prod" }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: "migration-database"
  annotations:
    argocd.argoproj.io/sync-options: Prune=confirm
  labels:
    helm.sh/chart: {{ include "kosmo.chart" . }}
    app.kubernetes.io/name: migration-database
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  vaultAuthRef: "vso-kubernetes-sync"
  mount: "secret"
  type: "kv-v2"
  path: "kubernetes/kosmo/prod/migration"
  refreshAfter: "5m"
  destination:
    name: {{ printf "%s-postgres-migration" .Release.Name | trunc 63 | trimSuffix "-" | quote }}
    create: true
    overwrite: true
    type: "kubernetes.io/basic-auth"
    labels:
      cnpg.io/reload: "true"
    transformation:
      includes:
        - "^username$"
        - "^password$"
{{- end }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: "api-database"
  annotations:
    argocd.argoproj.io/sync-options: Prune=confirm
  labels:
    helm.sh/chart: {{ include "kosmo.chart" . }}
    app.kubernetes.io/name: api-database
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  vaultAuthRef: "vso-kubernetes-sync"
  mount: "secret"
  type: "kv-v2"
  path: {{ printf "kubernetes/kosmo/%s/api-database" $env | quote }}
  refreshAfter: "5m"
  destination:
    name: {{ printf "%s-postgres-api" $releaseName | quote }}
    create: true
    overwrite: true
    type: "kubernetes.io/basic-auth"
    labels:
      cnpg.io/reload: "true"
    transformation:
      includes:
        - "^username$"
        - "^password$"
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: "worker-database"
  annotations:
    argocd.argoproj.io/sync-options: Prune=confirm
  labels:
    helm.sh/chart: {{ include "kosmo.chart" . }}
    app.kubernetes.io/name: worker-database
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  vaultAuthRef: "vso-kubernetes-sync"
  mount: "secret"
  type: "kv-v2"
  path: {{ printf "kubernetes/kosmo/%s/worker-database" $env | quote }}
  refreshAfter: "5m"
  destination:
    name: {{ printf "%s-postgres-worker" $releaseName | quote }}
    create: true
    overwrite: true
    type: "kubernetes.io/basic-auth"
    labels:
      cnpg.io/reload: "true"
    transformation:
      includes:
        - "^username$"
        - "^password$"
