{{- $app := .Values.expo -}}
{{- if ne (default true $app.enabled) false }}
{{- if $app.infisical.enabled }}
{{- $versionLabel := regexReplaceAll "[^A-Za-z0-9_.-]" $app.image.tag "-" | trunc 63 | trimAll "-" -}}
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: {{ printf "%s-expo" .Release.Name | trunc 63 | trimSuffix "-" }}
  labels:
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/name: expo
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ $versionLabel | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  authentication:
    kubernetesAuth:
      identityId: {{ $app.infisical.identityId }}
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: secret
        namespace: infisical
      secretsScope:
        projectId: {{ $app.infisical.projectId }}
        envSlug: {{ $app.infisical.envSlug }}
        secretsPath: /
  managedKubeSecretReferences:
    - secretName: {{ $app.infisical.secretName }}
      secretNamespace: {{ $.Release.Namespace }}
      creationPolicy: Owner
{{- end }}
{{- end }}
