apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ printf "%s-api" .Release.Name | trunc 63 | trimSuffix "-" }}
  labels:
    helm.sh/chart: {{ include "kosmo.chart" . }}
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.version | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    blueGreen:
      activeService: {{ printf "%s-api" .Release.Name | trunc 63 | trimSuffix "-" }}
      previewService: {{ printf "%s-api-preview" .Release.Name | trunc 63 | trimSuffix "-" }}
      autoPromotionEnabled: true
      previewReplicaCount: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: api
          image: {{ printf "%s:%s" .Values.image .Values.version | quote }}
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          args:
            - api
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-app" (include "kosmo.postgresName" .) | quote }}
                  key: password
            - name: DATABASE_URL
              value: {{ include "kosmo.databaseUrl" . | quote }}
          envFrom:
            - secretRef:
                name: env
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
